export CURRENT_SHELL="bash"
export DOT_FILES=$(dirname $(dirname $(readlink $BASH_SOURCE)))

# All things that are both ZSH and Bash compatible
source $DOT_FILES/shell/common.sh

# Git completion support in bash
source $DOT_FILES/git/git-completion

# Fix for mysql gem
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH	

# RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
