PATH=/usr/local/mysql/bin:$PATH


alias mysql=/usr/local/mysql/bin/mysql
alias mysqladmin=/usr/local/mysql/bin/mysqladmin

CDPATH=~/code:$CDPATH

[[ -f ~/.projects ]] && source ~/.projects

source ~/.bashrc